### PR TITLE
Nuxeo server panel

### PR DESCRIPTION
**Pull request by nelsonsilva**
Not sure if you're still working on this but i've been trying to switch to IDEA as my main IDE and it would be nice to add at least a couple more things to the plugin to bring it up to par with Nuxeo IDE.

This PR is just a couple of changes i've done to the plugin so it can just be used for discussing if this sort of thing should be merged. I can clean it up and open a new PR.

Basically I:
- Added missing action icons.
- Switched to make instead of compile.
- Started work on Nuxeo server panel.

### CODE REVIEW

**Comment by troger** [comment]
Hi Nelson,

Thanks for your PR!
We will review and merge it next week.

**Comment by troger** [comment]
I've created https://jira.nuxeo.com/browse/NXP-13940 to follow this.

**Comment by nelsonsilva** [comment]
Ok, i just updated this PR with a couple more changes (like i said, i can try to break it down into smaller PRs and commits to keep history clean and with proper issue links).

I had some local changes to the hotreload process and i just ammend by commit. Basically i tried to add support for parallel module compilation (which i use). I also have a local change, which i haven't yet commited, to toggle compilation on reload on/off, this allows me faster reloads when i'm just messing with resources or have a large number of modules to reload but am just working on one of them.

Regarding the server panel i really haven't given it much thought, i just use a killable process and start nuxeoctl with "console". This way i can use a ConsoleView to show the log and the process is properly killed (SIGINT). There's probably some IDEA component which already supports "tailing" log files but i haven't really looked into it. I also only added a button to start the server in debug mode.

In the future it would be nice to have the Nuxeo actions available in the server panel (reload, etc..) as well as a simple dialog that allows selecting which modules to reload since it can be tricky understanding which modules are currently hotreloadable as you have to go to the Nuxeo facet of each of those. (I just end up looking at the dev.bundles file most of the time).

**Comment by troger** [comment]
Hi Nelson,

In fact, I'll have time to work on that in our next sprint, in ~2 weeks.

In the mean time, I'm OK with you about splitting this PR in 2 new PRs:
- one for the new feature: the server panel
- one for the improvement: the parallel module compilation

For the Nuxeo facet, well, it's the common pattern of IntelliJ when adding some "functionality" to a module. Adding a dialog to list the different modules with the Nuxeo facet could be a good idea (but I'm not sure it's really required :)).

**Pull request closed without merging**
